[tool.poetry]
name = "api-task"
version = "0.1.0"
description = ""
authors = ["Igor Batischev <igor.bat2013@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
